jobs:
  include:
    - os: windows
      language: cpp
      script:
        - powershell
        - cd scripts
        - dir
        - build-mingw.bat Debug opengl
    - os: linux
      dist: focal
      language: cpp
      compiler: gcc
      script: cd scripts && ./build.sh Debug
    - os: linux
      dist: focal
      language: cpp
      compiler: gcc
      script: cd scripts && ./build.sh Debug opengl
    - os: linux
      dist: focal
      language: cpp
      compiler: gcc
      script: cd scripts && ./build.sh Release
    - os: linux
      dist: focal
      language: cpp
      compiler: gcc
      script: cd scripts && ./build.sh Release opengl
    - os: osx
      osx_image: xcode12.4
      language: cpp
      compiler: clang
      script: cd scripts && ./build.sh Debug opengl
    - os: osx
      osx_image: xcode12.4
      language: cpp
      compiler: clang
      script: cd scripts && ./build.sh Release opengl
before_install:
  - |
    if [ "${TRAVIS_OS_NAME}" == "windows" ]; then
    choco install -y 7zip
    fi
