language: c++
sudo: enabled
os:
  - osx
  
before_install:
  - cd deps
install:
  - chmod +x prepare.sh
  - ./prepare.sh

before_script:
  - cd ..
  - mkdir build
  - cd build
script:
  - cmake ..
  - cmake --build .


  
