environment:
  matrix:
    - job_name: Ubuntu Linux builds
      appveyor_build_worker_image: Ubuntu2004
      
    - job_name: MacOS builds
      appveyor_build_worker_image: macos-bigsur
      
    - job_name: Windows MinGW builds
      appveyor_build_worker_image: Visual Studio 2015
      
    - job_name: Windows VS 2019 builds
      appveyor_build_worker_image: Visual Studio 2019
  
for:
-
  matrix:
    only:
      - job_name: Ubuntu Linux builds
  
  test_script:
    - cd scripts && ./build.sh Debug
    - cd ..
    - git clean -fdx
    - cd scripts && ./build.sh Release
    - cd ..
    - git clean -fdx
    - cd scripts && ./build.sh Debug opengl
    - cd ..
    - git clean -fdx
    - cd scripts && ./build.sh Release opengl

-
  matrix:
    only:
      - job_name: MacOS builds
  install:
  - curl https://sdk.lunarg.com/sdk/download/1.2.189.0/mac/vulkansdk-macos-1.2.189.0.dmg -o vulkansdk-macos-1.2.189.0.dmg
  - sudo hdiutil attach vulkansdk-macos-1.2.189.0.dmg
  - sudo /Volumes/vulkansdk-macos-1.2.189.0/InstallVulkan.app/Contents/MacOS/InstallVulkan --root ~/VulkanSDK/1.2.189.0 --accept-licenses --default-answer --confirm-command install
  - sudo hdiutil detach /Volumes/vulkansdk-macos-1.2.189.0
  
  test_script:
  - cd scripts && ./build.sh Debug
  - cd ..
  - git clean -fdx
  - cd scripts && ./build.sh Release
  - cd ..
  - git clean -fdx
  - cd scripts && ./build.sh Debug opengl
  - cd ..
  - git clean -fdx
  - cd scripts && ./build.sh Release opengl
-
  matrix:
    only:
      - job_name: Windows MinGW builds

  install:
  - choco install vulkan-sdk
  - refreshenv
  - set SELECTED_MINGW=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0
  - set PATH=%PATH%;%SELECTED_MINGW%\mingw64\bin
  - rmdir /Q /S C:\msys64
  - rmdir /Q /S C:\MinGW
  - del "C:\Program Files\Git\usr\bin\sh.exe"
  
  test_script:
  - cd scripts && .\build-mingw.bat Debug
  - git clean -fdx
  - cd scripts && .\build-mingw.bat Release
  - git clean -fdx
  - cd scripts && .\build-mingw.bat Debug opengl
  - git clean -fdx
  - cd scripts && .\build-mingw.bat Release opengl
-
  matrix:
    only:
      - job_name: Windows VS 2019 builds

  install:
  - choco install vulkan-sdk
  - refreshenv
  
  test_script:
  - cd scripts && .\build-vs.bat Debug opengl
  - git clean -fdx
  - cd scripts && .\build-vs.bat Release opengl
  - git clean -fdx
  - cd scripts && .\build-vs.bat Debug opengl
  - git clean -fdx
  - cd scripts && .\build-vs.bat Release opengl

build: off
