environment:
  matrix:
    - job_name: Windows VS 2022 builds
      appveyor_build_worker_image: Visual Studio 2022
      
#    - job_name: Ubuntu Linux builds
#      appveyor_build_worker_image: Ubuntu2004
# There seems to be a problem on appveyor and the Linux virtual machine does not work for the moment:
# [00:00:17] N: Skipping acquire of configured file 'contrib/binary-i386/Packages' as repository 'http://download.virtualbox.org/virtualbox/debian focal InRelease' doesn't support architecture 'i386'
# [00:00:17] N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://apt.postgresql.org/pub/repos/apt focal-pgdg InRelease' doesn't support architecture 'i386'
# [00:00:17] N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://download.mono-project.com/repo/ubuntu stable-focal InRelease' doesn't support architecture 'i386'
# [00:00:17] E: Repository 'http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu focal InRelease' changed its 'Label' value from 'Modern Erlang packages for Ubuntu and Debian' to 'Latest (26.x) Erlang packages for Ubuntu and Debian'
# [00:00:17] N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
# [00:00:17] Command exited with code 100
# [00:00:17] Build failed

    - job_name: MacOS builds
      appveyor_build_worker_image: macos-bigsur
      
    - job_name: Windows MinGW builds
      appveyor_build_worker_image: Visual Studio 2015
      
for:

-
  matrix:
    only:
      - job_name: Windows VS 2022 builds
  
  test_script:
  - cd scripts && .\build-vs.bat Debug && cd ..
  - git clean -fdx
  - cd scripts && .\build-vs.bat Release && cd ..

-
  matrix:
    only:
      - job_name: Ubuntu Linux builds

  install:
  - sudo apt-get update
  - sudo apt-get -y install libgl-dev libglu1-mesa-dev glslang-tools libasound2-dev libx11-dev libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxau-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxdmcp-dev libxext-dev libxfixes-dev libxft-dev libxi-dev libxinerama-dev libxkbfile-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxrender-dev libxres-dev libxss-dev libxt-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev xtrans-dev libxcb-render0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev xkb-data libxcb-dri3-dev libxcb-util-dev

  test_script:
  - cd scripts && ./build.sh Debug && cd ..
  - git clean -fdx
  - cd scripts && ./build.sh Release && cd ..
  
-
  matrix:
    only:
      - job_name: MacOS builds
  
  test_script:
  - cd scripts && ./build.sh Debug && cd ..
  - git clean -fdx
  - cd scripts && ./build.sh Release && cd ..

-
  matrix:
    only:
      - job_name: Windows MinGW builds

  install:
  - echo this is a MinGW build
  - set SELECTED_MINGW=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0
  - set PATH=%PATH%;%SELECTED_MINGW%\mingw64\bin
  - rmdir /Q /S C:\msys64
  - rmdir /Q /S C:\MinGW
  - del "C:\Program Files\Git\usr\bin\sh.exe"

  test_script:
  - cd scripts && .\build-mingw.bat Debug opengl && cd ..
  - git clean -fdx
  - cd scripts && .\build-mingw.bat Release opengl && cd ..

build: off
